name: mongo_dart_query
version: 2.0.1
description: Query builder for mongo_dart 
homepage: https://github.com/mongo-dart/mongo_dart_query
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  bson: ^2.0.1
  meta: ^1.3.0
dev_dependencies:
  test: ^1.16.0
  lints: ^2.0.0
