name: mongo_dart_query
version: 4.1.0-1.0.dev
description: Query builder for mongo_dart
homepage: https://github.com/mongo-dart/mongo_dart_query
environment:
  sdk: ">=2.17.0 <4.0.0"

publish_to: none  
  
dependencies:
  bson: #^5.0.0
    path: ../bson
  meta: ^1.9.0
  fixnum: ^1.1.0

dev_dependencies:
  test: ^1.24.0
  lints: ^2.1.0
